[project]
name = "sketch_map_tool"
version = "2024.11.12.1"
description = " Create re-digitizable paper maps for offline data collection in the field."
readme = "README.md"
authors = ["HeiGIT <info@heigit.org>"]
license = "GNU Affero General Public License v3.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "celery[sqlalchemy,redis]>=5.4.0",
    "flask>=3.1.0",
    "flask-babel>=4.0.0",
    "flower>=2.0.1",
    "geojson>=3.2.0",
    "kaleido==0.2.1",
    "matplotlib>=3.10.0",
    "matplotlib-scalebar>=0.8.1",
    "neptune>=1.13.0",
    "numpy<=2",
    "opencv-python-headless>=4.10.0.84",
    "plotly>=5.24.1",
    "pymupdf>=1.25.1",
    "pyproj>=3.7.0",
    "pyzbar>=0.1.9",
    "qrcode>=8.0",
    "redis>=5.2.1",
    "reportlab>=4.2.5",
    "requests>=2.32.3",
    "sam-2",
    "setuptools>=75.6.0",
    "shapelysmooth>=0.2.0",
    "svglib>=1.5.1",
    "toml>=0.10.2",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "ultralytics>=8.3.55",
    "ultralytics_MB",
    "waitress>=3.0.2",
    "wheel>=0.45.1",
    "wtforms>=3.2.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "platform_system == 'Windows' or platform_system == 'Linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "platform_system == 'Windows' or platform_system == 'Linux'" },
]

ultralytics_MB = { git = "https://github.com/itisacloud/ultralytics_multiband_support.git", rev = "caf0b57b265d3c6761272ecf18a44b1605e9b25f" }
sam-2 = { git = "https://github.com/facebookresearch/segment-anything-2.git" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "approvaltests>=14.3.0",
    "geopandas>=1.0.1",
    "hypothesis>=6.123.2",
    "locust>=2.32.5",
    "opencv-python>=4.10.0.84",
    "pre-commit>=4.0.1",
    "psycopg2-binary>=2.9.10",
    "pytest>=8.3.4",
    "pytest-celery>=1.1.3",
    "pytest-rerunfailures>=15.0",
    "ruff>=0.8.4",
    "testcontainers>=4.9.0",
    "vcrpy>=7.0.0",
]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle Error
    "F",    # Pyflakes
    "I",    # isort
    "N",    # pep8-nameing
    "Q",    # flake8-quotes
    "W",    # pycodestyle Warning
    "C90",  # mccabe
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning"]
